version: '3.8'

services:
  yelb-ui:
    image: mreferre/yelb-ui:0.7
    ports:
      - "80:80"
    environment:
      - YELB_APPSERVER_ENDPOINT=http://yelb-appserver:4567
    networks:
      - odilia-net

  yelb-appserver:
    image: mreferre/yelb-appserver:0.5
    environment:
      - REDIS_SERVER_ENDPOINT=redis-server
      - DATABASE_SERVER_ENDPOINT=yelb-db
    networks:
      - odilia-net

  yelb-db:
    image: mreferre/yelb-db:0.5
    networks:
      - odilia-net

  redis-server:
    image: redis:4.0.2
    command: redis-server --appendonly yes
    networks:
      - odilia-net

networks:
  odilia-net:
    driver: bridge